micronaut:
  application:
    name: gradleStarter
  security:
    enabled: true
    interceptUrlMap:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
netty:
  default:
    allocator:
      max-order: 3

jackson:
  serialization:
    writeDatesAsTimestamps: false