micronaut:
  application:
    name: gradleStarter
  security:
    enabled: true
    basic-auth:
      enabled: false
    authentication: bearer
    interceptUrlMap:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'r6GXSOMvVzhc2FqGsbvxfLW6uhUtT4zy'
            validation:
              secret: 'r6GXSOMvVzhc2FqGsbvxfLW6uhUtT4zy'
netty:
  default:
    allocator:
      max-order: 3

jackson:
  serialization:
    writeDatesAsTimestamps: false